config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  
  
  root 'home#index'
  

  resources :categories
  resources :marks
  resources :products
  

end

app/models/category.rb
class Category < ActiveRecord::Base

	validates :name, presence: true


	has_and_belongs_to_many :products


end

app/models/mark.rb
class Mark < ActiveRecord::Base
	has_many :products

	validates :name, presence: true

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	validates :cod, presence: true
	validates :price, presence: true
	validates :description, length: { in: 6..400 }


	belongs_to :mark
	has_and_belongs_to_many :categories



	has_attached_file :image, styles: { medium: "650x350", home: "300x400" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	#validates :image, attachment_presence: true # no puede crearce sin imagen el producto.

  	scope :latest_four, -> { order('created_at desc').limit(4) }


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_marks
  before_action :set_categories

  protected


  def set_marks
  	@marks = Mark.all
  end

  def set_categories
  	@categories = Category.all
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]


  def show
  end


  private
   
    def set_category
      @category = Category.find(params[:id])
    end

   
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	 @latest_products = Product.latest_four
  end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :set_mark, only: [:show]



  def index
    @marks = Mark.all
  end

  
  def show
    @products = Product.where(mark_id: params[:id])
  end

  private
    
    def set_mark
      @mark = Mark.find(params[:id])
    end

   
    def mark_params
      params.require(:mark).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]
  before_action :authenticate_user!, only: [:show]
  
  def index
    @products = Product.all
  end

  def show
  end

  
  private
  
    def set_product
      @product = Product.find(params[:id])
    end

  
    def product_params
      params.require(:product).permit(:cod, :price, :description, :image, :mark_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row column text-center">

<h1>Lista de Categorias</h1>
	<% @categories.each do |category| %>
		<ul class="menu">
		<li><%= link_to category.name, category %></li>
		</ul>
	<% end %>

</div>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Productos <%= @category.name %></h1>
<%= render "partial/list" %>

app/views/home/index.html.erb
<div class="row column text-center">
<h2>Ultimos Productos</h2>
<hr>
</div>

<div class="row small-up-2 large-up-4">

  <% @latest_products.each do |product| %>
    <div class="column">
      <%= image_tag product.image.url(:home), class: 'thumbnail' %>
      <h5><%= link_to product.name, product %></h5>
      <p>Codigo:<%= product.cod %></p>
      <p><%= number_to_currency(product.price, unit: "$",separator: ",", delimiter: ".") %></p>
      <%=link_to "Comprar", product, class: "button expanded" %>
    </div>
  <% end %>

</div>

<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "E-commerce final-curso" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>

  <body>
  	<%= render "partial/nav" %>


  	<div data-alert class="alert-box info radius">
		  <p class="notice"><%= notice %></p>
    </div>
  	<div data-alert class="alert-box alert radius">
      	<p class="alert"><%= alert %></p>
  	</div>


    <%= yield %>

  </body>
</html>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row column text-center">
<h1>Lista de Marcas</h1>

<% @marks.each do |mark| %>
	<ul class="menu">
		<li><%= link_to mark.name, mark %></li>
	</ul>
<% end %>
</div>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row column text-center">

	<h1>Productos <%= @mark.name %></h1>
	<%= render "partial/list" %>
</div>

app/views/partial/_list.html.erb
<div class="row column text-center">

<div class="row small-up-2 large-up-4">
  <% @products.each do |product| %>
    <div class="column">
      <%= image_tag product.image.url(:home), class: 'thumbnail' %>
      <h5><%= link_to product.name, product %></h5>
      <p>Codigo:<%= product.cod %></p>
      <p><%= number_to_currency(product.price, unit: "$",separator: ",", delimiter: ".") %></p>
      <%=link_to "Comprar", product, class: "button expanded" %>
    </div>
  <% end %>

</div>
</div>

app/views/partial/_nav.html.erb
<div class="top-bar">
		<div class="top-bar-left">
			<ul class="menu">
				<li class="menu-text">E-commerce</li>
				<li><%= link_to "Productos", products_path %></li>
				<li class="menu">
					<%= link_to "Marcas", marks_path %>
      			</li>
      			<li class="menu">
					<%= link_to "Categorias", categories_path %>
      			</li>
			</ul>
	</div>
	<div class="top-bar-right">
		<ul class="menu">
			<% if user_signed_in? %>
				<li><%= current_user.email %></li>
				<li><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete %></li>
    		<% else %>	
				<li><%= link_to "Iniciar Sesion", new_user_session_path %></li>
			<% end %>
		</ul>
	</div>
	</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row column text-center">
	<h1>Productos</h1>

	<%= render "partial/list" %>

</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Imagen:</strong>  
</p>

<div class="row">
  <div class="medium-6 columns">
    <%= image_tag @product.image.url(:medium) %>
  </div>
</div>

<div class="medium-6 large-5 columns">
  <h3><%= @product.name %></h3>
  <h5>Descripcion</h5>
  <p><%= @product.description %></p>
  <div class="row">
    <h5>Marca</h5>
    <p><%= @product.mark.name %></p>
    <div class="small-3 columns">
      <h5>Cantidad</h5>
    </div>
    <div class="small-3 columns">
      <input type="text" id="middle-label" value="1">
    </div>
    <div class="small-6 columns">
        <a href="#" class="button large expanded">Agregar al carrito</a>
    </div>
  </div>
  </div>